categories:
  - name: "Еда"
    patterns:
      - "PAYINFOTECH"
      - "VKUSVILL"
      - "SAMOKAT"
      - "5411"
      - "AZBUKAVKUSA"
      - "YANDEX\\*541"
      - "YANDEX\\*5411\\*EDA"
      - "VPROK"
      - "VV_"

  - name: "Кафе, посиделки"
    patterns:
      - "KOFEMANIYA"
      - "FRANK"
      - "BASTA"
      - "BUKHANKA"
      - "RESTORAN"
      - "LPITTORE"
      - "SURF"
      - "COFFEE"
      - "BURGER HEROES"

  - name: "Заказ еды"
    patterns:
      - "5814"
      - "YAKITORIYA"

  - name: "Семья и личные расходы. Медицина"
    patterns:
      - "АРТЕКА"
      - "DOCDENT"
      - "MED"
      - "MSKAPT"
      - "LENINSKY"
      - "AU \\d{3}"

  - name: "Бытовые расходы"
    patterns:
      - "SBER\\*5732\\*MEGAMARKET"

  - name: "Аппаратура"
    patterns:
      - "ALIEXPRESS"
      - "ПЕРЕВОД ПО НОМЕРУ ТЕЛЕФОНА \\+79267660077"

  - name: "Ком. платежи: Интернет"
    patterns:
      - "MGTS"

  - name: "Транспорт. Транспорт"
    patterns:
      - "METRO"
      - "TRANSPORT"

  - name: "Обеды"
    patterns:
      - "FLOOR TEA"

  - name: "Уборка"
    patterns:
      - "GETAIRO"

  - name: "Ком. платежи. Вернадского 54"
    patterns:
      - "ZHKU"

  - name: "Электричество"
    patterns:
      - "MOSENERGOSBYT"

  - name: "Дом. Аренда"
    patterns:
      - "SKLADNO"

  - name: "Праздники, Подарки"
    patterns:
      - "SOYUZCVETTORG"
      - "VSEVSAD"

  - name: "Косметология и уход"
    patterns:
      - "WAXANDGO"

  - name: "Стрижка"
    patterns:
      - "LIVECURLY"

  - name: "Дети. Одежда"
    patterns:
      - "WB"
      - "WILDBERRIES"
      - "DETSKIY MIR"

  - name: "Дети. Образование | Сад"
    patterns:
      - "03224643450000007300"

  - name: "Доставка"
    patterns:
      - "DOSTAVKA"
      - "POCHTA"
      - "4215"

  - name: "Такси"
    patterns:
      - "TAXI"
      - "412"
      - "4121"

  - name: "Долги. Кредитная карта"
    patterns:
      - "КОМИССИЯ ЗА ОПЕРАЦИЮ В КРЕДИТНЫХ ОРГАНИЗАЦИЯХ"

  - name: "Одежда"
    patterns:
      - "LAMODA"

  - name: "Путешествия. Расходы на жилье"
    patterns:
      - "TRAVEL"
      - "AVIA"

type_settings:
  Tinkoff_Platinum:
    class: "01 Личное"
    contractor: ""
  Tinkoff:
    class: "01 Личное"
    contractor: ""
  Visa_Gold_Aeroflot:
    class: "03 Родные, близкие"
    contractor: "! М"
  default:
    class: "01 Личное"
    contractor: ""
