pdf_types:
  Tinkoff_Platinum:
    patterns:
      - "Номер договора: \\s*0589803758" # Номер договора
    columns:
      - 0
      - 3
      - 4
      - 5
    start_marker: "Дата и время"
    end_marker: "Пополнения:"

  Tinkoff:
    patterns:
      - "Номер договора: \\s*5174820778" # Номер договора
      - "Номер лицевого счета: \\s*40817810500013965387" # Номер лицевого счета
    columns:
      - 0
      - 3
      - 4
      - 5
    start_marker: "Дата и время"
    end_marker: "Пополнения:"

  Visa_Gold_Aeroflot:
    patterns:
      - "\\s*40817 810 8 0018 3216861" # Номер счёта
      - "Кредитная Аэрофлот" # Карта
    columns:
      - 0
    start_marker: "Расшифровка операций за период"
    end_marker: "Дергунова К. А."
    remove_rows_by_text:
      - "Продолжение на следующей странице"
      - "Страница"
      - "ДАТА ОПЕРАЦИИ"
      - "Дата обработки¹ и код авторизации"
      - "КАТЕГОРИЯ"
      - "Описание операции"
      - "СУММА В РУБЛЯХ"
      - "Сумма в валюте операции"
      - "ОСТАТОК СРЕДСТВ"
      - "Для проверки подлинности"
      - "1. Зайдите в приложение"
      - "2. Нажмите кнопку в верхнем"
      - "3. Получите документ в электронном"
      - "Предоставляя QR-код третьим лицам"
      - "ВЫПИСКА ПО СЧЁТУ КРЕДИТНОЙ КАРТЫ"
    # remove_rows_by_position: # не используется

  Yandex:
    patterns:
      - "\\s*40817810920000122100" # Номер счёта
    columns:
      - 0
    start_marker: "Выписка по Договору за период с "
    end_marker: "Исходящий остаток за "
    remove_rows_by_text:
      - "Входящий остаток на "
      - "Продолжение на следующей странице"
      - "Страница "
      - "Описание операции"
      - "Дата и время"
      - "операции"
      - "МСК"
      - "Дата"
      - "обработки"
      - "МСК"
      - "Карта"
      - "Сумма в валюте"
      - "Договора"
      - "^[\"']?[0-9\xa0]+,[0-9]{2} ₽[\"']?$" # Суммы без +/–, с учетом \xa0 и кавычек


      # - "^\"?[^+-][0-9\u00A0]+,[0-9]{2} ₽\"?$"
      # - "^[^+-][0-9\u00A0]+,[0-9]{2} ₽$" # Суммы без +/– (например, "1 052,45 ₽")

      # - "^[+-]?\\d{1,3}(?: \\d{3})*,\\d{2} ₽$" # Суммы вида "1 052,45 ₽" (с пробелами и ₽)
      # - "^[+-]?\\d+,\\d{2} ₽$" # Суммы вида "1052,45 ₽" (без пробелов)
      # - "^[+-]?\\d{1,3}(?: \\d{3})*,\\d{2}$" # Суммы вида "1 052,45" (без ₽)
      # - "^[+-]?\\d+,\\d{2}$" # Суммы вида "1052,45" (без пробелов и ₽)

      # - "\\b\\d{1,3}(?: \\d{3})*,\\d{2} ₽\\b" # Сумма вида "1 052,45 ₽" (в любом месте строки)
      # - "\\b\\d+,\\d{2} ₽\\b" # Сумма вида "1052,45 ₽" (без пробелов)
      # - "\\b\\d{1,3}(?: \\d{3})*,\\d{2}\\b" # Сумма вида "1 052,45" (без ₽)
      # - "\\b\\d+,\\d{2}\\b" # Сумма вида "1052,45" (без пробелов и ₽)
