pdf_types:
  Tinkoff_Platinum:
    patterns:
      - "Номер договора: \\s*0589803758" # Номер договора
    columns:
      - 0
      - 3
      - 4
      - 5
    start_marker: "Дата и время"
    end_marker: "Пополнения:"

  Tinkoff:
    patterns:
      - "Номер договора: \\s*5174820778" # Номер договора
      - "Номер лицевого счета: \\s*40817810500013965387" # Номер лицевого счета
    columns:
      - 0
      - 3
      - 4
      - 5
    start_marker: "Дата и время"
    end_marker: "Пополнения:"

  Visa_Gold_Aeroflot:
    patterns:
      - "\\s*40817 810 8 0018 3216861" # Номер счёта
      - "Кредитная Аэрофлот" # Карта
    columns:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      # - 6
    start_marker: "ДАТА ОПЕРАЦИИ" # (МСК)"
    end_marker: "Дата формирования"
    # remove_rows_by_position:
    # first: 1 # удалить первые 3 строки
    # last: 2 # удалить последние 2 строки
    # indices: [0, 5, 10]  # удалить строки с указанными индексами
