# config/settings.yaml
# Общие настройки бота
LOG_LEVEL: INFO # Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_lines_to_show: 50 # Количество последних строк лога для отображения в текстовом виде
export_last_import_ids_count: 10 # Количество последних import_id для отображения в фильтре экспорта
backup_days_to_keep: 15 # Настройки хранения бэкапов БД
log_file_backup_count: 15 # Количество старых файлов логов для хранения (backupCount для TimedRotatingFileHandler)

# /////////////////////////////
# /////////////////////////////
# /////////////////////////////
# Другие настройки могут быть добавлены здесь в будущем
# например:
# max_file_size_mb: 10
# default_export_days_range: 30

# !!!Надо определить что это 2122-2128 и надо ли вынести в эти настройки
# file = await document.get_file(
#     read_timeout=30,
#     connect_timeout=30,
#     pool_timeout=30,
#     write_timeout=30
# )
# downloaded_file = await file.download_to_drive()
