timeouts:
  download_timeout: 10 # Таймаут загрузки файла (секунды)
  processing_timeout: 20 # Таймаут обработки файла (секунды)
  request_timeout: 10 # Таймаут для обычных запросов (секунды)
  delay_between_operations: 5 # Задержка между операциями (секунды)
